import { PlotMarker } from './types'

// Sample plot data for demonstration
export const SAMPLE_PLOTS: PlotMarker[] = [
  {
    id: '1',
    title: 'Sunny 5-Acre Organic Farm Plot',
    latitude: 35.5951,
    longitude: -82.5515,
    acreage: 5,
    pricePerMonth: 400,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    city: 'Asheville',
    state: 'NC',
    soilType: ['LOAM'],
    waterAccess: ['WELL', 'IRRIGATION'],
    hasIrrigation: true,
    hasFencing: true,
    hasGreenhouse: false,
    averageRating: 4.8,
    ownerName: 'Harold Thompson',
  },
  {
    id: '2',
    title: 'Creek-Side 2-Acre Garden Plot',
    latitude: 35.6145,
    longitude: -82.5698,
    acreage: 2,
    pricePerMonth: 250,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800'],
    city: 'Asheville',
    state: 'NC',
    soilType: ['LOAM', 'SILT'],
    waterAccess: ['STREAM', 'WELL'],
    hasIrrigation: false,
    hasFencing: true,
    hasGreenhouse: false,
    averageRating: 4.9,
    ownerName: 'Sarah Chen',
  },
  {
    id: '3',
    title: 'Premium 10-Acre Farmstead',
    latitude: 35.5698,
    longitude: -82.6015,
    acreage: 10,
    pricePerMonth: 850,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    city: 'Leicester',
    state: 'NC',
    soilType: ['LOAM'],
    waterAccess: ['WELL', 'POND', 'IRRIGATION'],
    hasIrrigation: true,
    hasFencing: true,
    hasGreenhouse: true,
    averageRating: 5.0,
    ownerName: 'Devon Martinez',
  },
  {
    id: '4',
    title: 'Urban Garden Plot - 0.5 Acre',
    latitude: 35.6082,
    longitude: -82.5540,
    acreage: 0.5,
    pricePerMonth: 150,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800'],
    city: 'Asheville',
    state: 'NC',
    soilType: ['LOAM'],
    waterAccess: ['MUNICIPAL'],
    hasIrrigation: true,
    hasFencing: true,
    hasGreenhouse: false,
    averageRating: 4.5,
    ownerName: 'Community Garden Collective',
  },
  {
    id: '5',
    title: 'Mountain View 3-Acre Plot',
    latitude: 35.6298,
    longitude: -82.5201,
    acreage: 3,
    pricePerMonth: 350,
    status: 'RENTED',
    images: ['https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800'],
    city: 'Weaverville',
    state: 'NC',
    soilType: ['CLAY', 'LOAM'],
    waterAccess: ['WELL'],
    hasIrrigation: false,
    hasFencing: false,
    hasGreenhouse: false,
    averageRating: 4.7,
    ownerName: 'James Wilson',
  },
  {
    id: '6',
    title: 'Valley Bottom 7-Acre Farm',
    latitude: 35.5423,
    longitude: -82.5287,
    acreage: 7,
    pricePerMonth: 600,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800'],
    city: 'Arden',
    state: 'NC',
    soilType: ['LOAM', 'SILT'],
    waterAccess: ['STREAM', 'WELL', 'IRRIGATION'],
    hasIrrigation: true,
    hasFencing: true,
    hasGreenhouse: true,
    averageRating: 4.6,
    ownerName: 'Emily Rodriguez',
  },
  {
    id: '7',
    title: 'Hilltop Orchard Plot - 4 Acres',
    latitude: 35.6512,
    longitude: -82.5823,
    acreage: 4,
    pricePerMonth: 375,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=800'],
    city: 'Weaverville',
    state: 'NC',
    soilType: ['CLAY'],
    waterAccess: ['WELL'],
    hasIrrigation: false,
    hasFencing: true,
    hasGreenhouse: false,
    ownerName: 'Robert & Linda Patterson',
  },
  {
    id: '8',
    title: 'Riverside 6-Acre Permaculture Site',
    latitude: 35.5789,
    longitude: -82.4698,
    acreage: 6,
    pricePerMonth: 500,
    status: 'ACTIVE',
    images: ['https://images.unsplash.com/photo-1589923188900-85dae523342b?w=800'],
    city: 'Black Mountain',
    state: 'NC',
    soilType: ['LOAM'],
    waterAccess: ['STREAM', 'IRRIGATION'],
    hasIrrigation: true,
    hasFencing: false,
    hasGreenhouse: false,
    averageRating: 4.9,
    ownerName: 'Green Valley Farms',
  },
]
